name: Out of Office Request Form
description: Request time off
title: "OOO: [GITHUB_HANDLE] from [MM/DD] to [MM/DD]"
labels: ["triage"]
assignees:
  - a-a-ron
body:
  - type: markdown
    attributes:
      value: |
        ![11OUTOFTHEOFFICE-superJumbo](https://user-images.githubusercontent.com/6351798/164553799-fb9a52a8-4fe8-4fde-95ed-97cade3a9e69.gif) </br> <div align="center"><h1> Yay! We're glad you're taking some time off!</h1> </br></br> <h3>Please fill out the below form so the team knows what dates you're requesting and if you need help covering anything while you're out.</h3></div> 
  - type: input
    id: ooo-timeframe
    attributes:
      label: What date(s) are you requesting time off?
  - type: dropdown
    id: ships
    attributes:
      label: Do you need someone to cover for you during your time OOO?
      multiple: true
      options:
        - "Yes"
        - "No"
  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating systems have you used?
      description: You may select more than one.
      options:
        - label: macOS
        - label: Windows
        - label: Linux
