name: Out of Office Request Form
description: Request time off
title: "OOO: [GITHUB_HANDLE] from [MM/DD] to [MM/DD]"
labels: ["triage"]
assignees:
  - a-a-ron
body:
  - type: input
    id: ooo-timeframe
    attributes:
      label: What date(s) are you requesting time off?
